### ISSUE TITLE
Has

### ISSUE THREAD

**Issue by tanelam** [Jukica/pjs-capstone-lodash#3]
https://github.com/Jukica/pjs-capstone-lodash/blob/51a8f97d721a1f7d44e94867382e42c42ac15969/Lodash/_.js#L38-L46

This could be simplified a bit. The `!` operator itself returns `true` or `false`. More info [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Logical_NOT_(!))!

**return obj[key] !== undefined**

**Comment by Jukica** [comment]
Thanks for the tip!
