### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tanelam** [Jukica/pjs-capstone-lodash#5]
### Criteria 1: Functionality

- Score Level: 4
- Comment(s): You did a great job on this project. You were able to get all the tests to pass with green lights! Your functions were well implemented and efficient. As a future goal, you can identify and implement additional edge cases or additional methods beyond the original ten.

### Criteria 2: Code Style - Formatting

- Score Level: 4
- Comment(s): Very nice work keeping everything neat and readable using consistent indentation. Also, great job using semicolons when you needed to end a line. There are some parts of your code where you're using one line between functions, and there are other times where you are using 2 or 3 lines to separate your functions. Try to keep your lines consistent (doesn't matter if you use one line or more, just be consistent in what you choose) this will make your code look cleaner and it would be easier for other developers to read. 

### Criteria 3: Code Style - JavaScript Techniques

- Score Level: 4
- Comment(s): In general, great work getting everything set up. Your code is readable, but some minor optimizations are still available. Great job taking advantage of the built-in methods and previously written functions throughout your program.

### Overall Score: 12/12
Great work on this project! 👏😄

**Comment by Jukica** [comment]
Thanks for the review and for the cheers, much appreciated! :)
